bundler_args: --without yard guard metrics benchmarks
before_install:
  - gem install bundler --pre
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.3
branches:
  only:
    - /^release-.*$/
services:
  - sqlite3
  - mysql
  - postgresql
before_script:
  - mysql -e "create database datamapper_alternate_tests;"
  - mysql -e "create database datamapper_default_tests;"
  - psql  -c "create database datamapper_default_tests;" -U postgres
  - psql  -c "create database datamapper_alternate_tests;" -U postgres
script: "bundle exec rake spec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2
env:
  - "GIT_BRANCH=release-1.2 ADAPTER=in_memory"
  - "GIT_BRANCH=release-1.2 ADAPTER=yaml"
  - "GIT_BRANCH=release-1.2 ADAPTER=sqlite"
  - "GIT_BRANCH=release-1.2 ADAPTER=mysql DM_DB_USER=root DM_DB_PASSWORD=''"
  - "GIT_BRANCH=release-1.2 ADAPTER=postgres DM_DB_USER=postgres DM_DB_PASSWORD=''"
matrix:
  allow_failures:
    - rvm: 2.2.0
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
